import { AppState } from "@/types";

export const getInitialState = (): AppState => ({
  users: [
    {
      id: "admin",
      username: "admin",
      password: "admin",
      role: "admin",
      name: "Администратор",
      isActive: true,
      city: "Рязань",
    },
    {
      id: "user1",
      username: "user1",
      password: "1234",
      role: "judge",
      name: "Бурцев Дмитрий",
      isActive: true,
      city: "Рязань",
    },
    {
      id: "user2",
      username: "user2",
      password: "1234",
      role: "judge",
      name: "Читаев Илья",
      isActive: true,
      city: "Рязань",
    },
    {
      id: "user3",
      username: "user3",
      password: "1234",
      role: "judge",
      name: "Цветков Ефим",
      isActive: true,
      city: "Рязань",
    },
    {
      id: "user4",
      username: "user4",
      password: "1234",
      role: "player",
      name: "Шлёнкин Юрий",
      isActive: true,
      city: "Рязань",
    },
    {
      id: "user5",
      username: "user5",
      password: "1234",
      role: "player",
      name: "Спешнев Михаил",
      isActive: true,
      city: "Рязань",
    },
    {
      id: "user6",
      username: "user6",
      password: "1234",
      role: "player",
      name: "Лазутин Илья",
      isActive: true,
      city: "Рязань",
    },
    {
      id: "user7",
      username: "user7",
      password: "1234",
      role: "player",
      name: "Ферестан",
      isActive: true,
      city: "Рязань",
    },
    {
      id: "user8",
      username: "user8",
      password: "1234",
      role: "player",
      name: "Пятахин Герман",
      isActive: true,
      city: "Рязань",
    },
    {
      id: "user9",
      username: "user9",
      password: "1234",
      role: "player",
      name: "Читаев Демьян",
      isActive: true,
      city: "Рязань",
    },
    {
      id: "user10",
      username: "user10",
      password: "1234",
      role: "player",
      name: "Морозов Артём",
      isActive: true,
      city: "Рязань",
    },
    {
      id: "user11",
      username: "user11",
      password: "1234",
      role: "player",
      name: "Ермилов Виталий",
      isActive: true,
      city: "Рязань",
    },
    {
      id: "user12",
      username: "user12",
      password: "1234",
      role: "player",
      name: "Капитанский Даниил",
      isActive: true,
      city: "Рязань",
    },
  ],
  currentUser: null,
  currentPage: "rating",
  players: [
    {
      id: "user1",
      name: "Бурцев Дмитрий",
      city: "Рязань",
      rating: 1200,
      tournaments: 0,
      wins: 0,
      losses: 0,
      draws: 0,
    },
    {
      id: "user2",
      name: "Читаев Илья",
      city: "Рязань",
      rating: 1200,
      tournaments: 0,
      wins: 0,
      losses: 0,
      draws: 0,
    },
    {
      id: "user3",
      name: "Цветков Ефим",
      city: "Рязань",
      rating: 1200,
      tournaments: 0,
      wins: 0,
      losses: 0,
      draws: 0,
    },
    {
      id: "user4",
      name: "Шлёнкин Юрий",
      city: "Рязань",
      rating: 1200,
      tournaments: 0,
      wins: 0,
      losses: 0,
      draws: 0,
    },
    {
      id: "user5",
      name: "Спешнев Михаил",
      city: "Рязань",
      rating: 1200,
      tournaments: 0,
      wins: 0,
      losses: 0,
      draws: 0,
    },
    {
      id: "user6",
      name: "Лазутин Илья",
      city: "Рязань",
      rating: 1200,
      tournaments: 0,
      wins: 0,
      losses: 0,
      draws: 0,
    },
    {
      id: "user7",
      name: "Ферестан",
      city: "Рязань",
      rating: 1200,
      tournaments: 0,
      wins: 0,
      losses: 0,
      draws: 0,
    },
    {
      id: "user8",
      name: "Пятахин Герман",
      city: "Рязань",
      rating: 1200,
      tournaments: 0,
      wins: 0,
      losses: 0,
      draws: 0,
    },
    {
      id: "user9",
      name: "Читаев Демьян",
      city: "Рязань",
      rating: 1200,
      tournaments: 0,
      wins: 0,
      losses: 0,
      draws: 0,
    },
    {
      id: "user10",
      name: "Морозов Артём",
      city: "Рязань",
      rating: 1200,
      tournaments: 0,
      wins: 0,
      losses: 0,
      draws: 0,
    },
    {
      id: "user11",
      name: "Ермилов Виталий",
      city: "Рязань",
      rating: 1200,
      tournaments: 0,
      wins: 0,
      losses: 0,
      draws: 0,
    },
    {
      id: "user12",
      name: "Капитанский Даниил",
      city: "Рязань",
      rating: 1200,
      tournaments: 0,
      wins: 0,
      losses: 0,
      draws: 0,
    },
  ],
  cities: [{ id: "ryazan", name: "Рязань" }],
  tournamentFormats: [
    { id: "sealed", name: "Силед", coefficient: 1 },
    { id: "draft", name: "Драфт", coefficient: 1 },
    { id: "constructed", name: "Констрактед", coefficient: 1 },
  ],
  tournaments: [
    {
      id: "1",
      name: "Релиз",
      date: "2025-09-06",
      city: "Рязань",
      format: "Sealed",
      description: "Турнир по формату Sealed в Рязани",
      isRated: true,
      swissRounds: 5,
      topRounds: 0,
      participants: [
        "user1",
        "user2",
        "user3",
        "user4",
        "user5",
        "user6",
        "user7",
        "user8",
        "user9",
        "user10",
        "user11",
        "user12",
      ],
      status: "active" as const,
      rounds: [],
      currentRound: 0,
    },
  ],
  showLogin: false,
});
